#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']

get_user:
  path:     /api/user
  controller: App\Controller\AuthController::getCompleteUser
  methods:  [GET]
